# Generated by Django 5.1.5 on 2025-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='compensations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='deliverer_compensation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
